### ISSUE TITLE
Parse sourced files as well

### ISSUE THREAD

**Issue by jrhorn424** [csexton/infect#5]
One thing I liked about `vundle` was the ability to refactor my `.vimrc` into different files and call them all from `.vimrc`. For example:

``` vim
" $HOME/.vimrc
source $HOME/.vimrc.colors

" $HOME/.vimrc.colors
set t_Co=256
set background=dark
"=bundle altercation/vim-colors-solarized
let g:solarized_termtrans = 1
colorscheme solarized
syntax on
highlight clear SignColumn
```

Unfortunately, `infect` can't see magic comments hidden in these sourced files. It'd be great if it did!

**Comment by csexton** [comment]
Kudos for cleaning up old issues. :100:

😢 for me not fixing this, coulda been nice.

**Comment by jrhorn424** [comment]
@csexton 😆 nothing to worry about! My GitHub dashboard is so full of junk, sometimes when I want to shut off 🧠 , I practice that digital hygiene.

I sort of feel guilty for not doing a PR 1) back when I was using `vim` exclusively and 2) since I eventually learned teh codez.
